/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.awt.CardLayout; 
import javax.swing.*;
import model.User;
/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {
      private JPanel CreateUserPanel;
      private JPanel ViewUserPanel;
      private CardLayout cardLayout; 
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
//        cardLayout = (CardLayout) bottomPanel.getLayout();
        //bottomPanel = new javax.swing.JPanel(new CardLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        createUser = new javax.swing.JButton();
        viewUser = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setBackground(new java.awt.Color(255, 255, 255));
        SplitPane.setDividerLocation(100);
        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPanel.setBackground(new java.awt.Color(255, 204, 204));

        createUser.setBackground(new java.awt.Color(204, 0, 102));
        createUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createUser.setForeground(new java.awt.Color(255, 255, 255));
        createUser.setText("Create User");
        createUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserActionPerformed(evt);
            }
        });

        viewUser.setBackground(new java.awt.Color(0, 0, 204));
        viewUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewUser.setForeground(new java.awt.Color(255, 255, 255));
        viewUser.setText("View Users");
        viewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(createUser, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(viewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewUser, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(createUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SplitPane.setTopComponent(topPanel);

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setMinimumSize(new java.awt.Dimension(100, 400));
        bottomPanel.setPreferredSize(new java.awt.Dimension(535, 400));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(bottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserActionPerformed
        // TODO add your handling code here:
        /*CreateUserPanel createUserPanel = new CreateUserPanel(bottomPanel);
        bottomPanel.add(createUserPanel, "create");
        CardLayout cardLayout = (CardLayout) bottomPanel.getLayout(); 
        cardLayout.show(bottomPanel, "create"); */
        
        
       /* bottomPanel.setLayout(new CardLayout());
      CreateUserPanel = new CreateUserPanel(bottomPanel);
        ViewUserPanel = new JPanel();

        bottomPanel.add("create", CreateUserPanel); 
        bottomPanel.add("view", ViewUserPanel);*/
        
        /*CreateUserPanel createUserPanel = new CreateUserPanel(bottomPanel);
        bottomPanel.add(createUserPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);*/
        
        CreateUserPanel createUserPanel = new CreateUserPanel(bottomPanel);
    bottomPanel.add(createUserPanel, "create");

    // Initialize CardLayout only if it's not set
    if (!(bottomPanel.getLayout() instanceof CardLayout)) {
        bottomPanel.setLayout(new CardLayout());
    }
    
    CardLayout cardLayout = (CardLayout) bottomPanel.getLayout();
    cardLayout.show(bottomPanel, "create");
    }//GEN-LAST:event_createUserActionPerformed

    private void viewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUserActionPerformed
        // TODO add your handling code here:
        User newUser = new User();
        ViewUserPanel viewUserPanel= new ViewUserPanel(bottomPanel);
        bottomPanel.add("view", viewUserPanel);
        
        CardLayout cardLayout = (CardLayout) bottomPanel.getLayout(); 
        cardLayout.show(bottomPanel, "view");
        
       /* User newUser = new User();
        ViewUserPanel viewUserPanel = new ViewUserPanel(bottomPanel);
        bottomPanel.add(ViewUserPanel, "view");
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.show(bottomPanel, "details");*/
       
       /*ViewUserPanel viewUserPanel = new ViewUserPanel(null);
        bottomPanel.add(viewUserPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);*/
    }//GEN-LAST:event_viewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton createUser;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton viewUser;
    // End of variables declaration//GEN-END:variables
}
